### ISSUE TITLE
Connect Data Model 

### ISSUE THREAD

**Issue by yiranzhao0722** [uwcirg/mpower_api#2]
Main goal: 
Connect back-end to data model. 

Sub goals:
- [x] Select which package for representing the data base -> SQLAlchemy?
- [x] Initialize the database scheme and populates with testing data
- [x] Host the database in docker container 
- [x] Connect using Flask
- [x] Connect with SQLAlchemy; model dependencies

**Comment by pmanko** [comment]
Closed by f2c3dc5d7a6647837f3cd27991e36da3ecf67bb0 💯
